---
# tasks file for ssh_key
- stat:
    path: "{{ id_rsa_file }}"
  register: op

- name: Generate SSH key "{{ssh_key_filename}}" on master
  user:
    name: "root"
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_file: /root/.ssh/{{ssh_key_filename}}
    ssh_key_passphrase: "{{ssh_passphrase}}"
    force: no

- debug: 
    msg: "Key pair already exists. Using the same key."
  when: op.stat.exists

- name: Copy public key to the agents
  command: sshpass -p "{{ root_password }}" ssh-copy-id -i "{{ id_rsa_file }}" root@"{{ item }}" -f -o StrictHostKeyChecking=no
  with_items:
    - "{{ agents }}"